/**
 * n8n contract (phase 10 M4): what the backend and the n8n workflows promise each other,
 * GENERATED from the code — never edited by hand.
 *
 *   pnpm --filter @smartops/api n8n:contract     # rewrite n8n/contract.json
 *
 * - backend → n8n: the "message.ready" webhook (payload schema + shared-secret header);
 * - n8n → backend: every /api/v1/internal/* route (method, path, JSON Schema of the body /
 *   params) behind the internal API key header.
 * test/unit/n8n-contract.test.ts fails when the file is stale, and checks every HTTP node of the
 * exported workflows against the SAME Zod schemas the API validates with.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  MESSAGE_READY,
  MESSAGE_READY_VERSION,
  messageReadyPayloadSchema,
} from "../../src/modules/integration/message-ready.js";
import { INTERNAL_API_KEY_HEADER } from "../../src/common/middleware/internal-api-key.js";
import { N8N_SECRET_HEADER } from "../../src/modules/integration/n8n-delivery.js";
import { INTERNAL_ROUTE_SCHEMAS } from "../../src/modules/internal/internal.routes.js";

export const CONTRACT_FILE = fileURLToPath(
  new URL("../../../../n8n/contract.json", import.meta.url),
);
export const INTERNAL_PREFIX = "/api/v1/internal";

type RouteSchemas = { body?: z.ZodType; params?: z.ZodType };

const jsonSchema = (schema: z.ZodType) => {
  const out = z.toJSONSchema(schema) as Record<string, unknown>;
  delete out.$schema; // declared once at the top of the file
  return out;
};

export function buildContract() {
  const routes = Object.fromEntries(
    Object.entries(INTERNAL_ROUTE_SCHEMAS as Record<string, RouteSchemas>).map(([key, s]) => {
      const [method, path] = key.split(" ") as [string, string];
      return [
        `${method} ${INTERNAL_PREFIX}${path}`,
        {
          ...(s.params ? { params: jsonSchema(s.params) } : {}),
          ...(s.body ? { body: jsonSchema(s.body) } : {}),
        },
      ];
    }),
  );
  return {
    $comment:
      "GENERATED by `pnpm --filter @smartops/api n8n:contract` from the API code. Do not edit: a test fails when it is stale.",
    $schema: "https://json-schema.org/draft/2020-12/schema",
    backendToN8n: {
      event: MESSAGE_READY,
      version: MESSAGE_READY_VERSION,
      method: "POST",
      auth: { header: N8N_SECRET_HEADER, credential: "SmartOps webhook secret" },
      payload: jsonSchema(messageReadyPayloadSchema),
    },
    n8nToBackend: {
      baseUrlFrom: "Config node → apiBaseUrl (…/api/v1)",
      auth: { header: INTERNAL_API_KEY_HEADER, credential: "SmartOps API" },
      routes,
    },
  };
}

export const renderContract = () => `${JSON.stringify(buildContract(), null, 2)}\n`;

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(CONTRACT_FILE, renderContract());
  process.stdout.write(`n8n contract written: ${CONTRACT_FILE}\n`);
}
